identifier: kfe2d4b8tej76ec1
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: tnc-scully
homeFolder: /media/ericambiel/BKP/Projetos/pessoais/tnc-scully
distFolder: dist/tnc-scully
outDir: /media/ericambiel/BKP/Projetos/pessoais/tnc-scully/dist/static
handle404: ''
